version: '3'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - database_data:/var/lib/postgresql/data


volumes:
  database_data: